# Generated by Django 6.0.1 on 2026-02-07 12:30

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_thread_replies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
