# Generated by Django 6.0.1 on 2026-02-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0004_thread_likes_count_alter_thread_content_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="thread",
            name="tags",
            field=models.ManyToManyField(blank=True, to="forum.tags"),
        ),
    ]
