# Generated by Django 6.0.1 on 2026-02-11 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0007_threadresource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="resources",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
    ]
