# Generated by Django 6.0.1 on 2026-02-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0008_remove_thread_resources_delete_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="content",
            field=models.TextField(),
        ),
    ]
